name: CI
on:
  push:
    branches:
      - master
env:
  VALINE_APPID: ${{ secrets.VALINE_APPID }}
  VALINE_APPKEY: ${{ secrets.VALINE_APPKEY }}
  SIYUAN_HOST: ${{ secrets.SIYUAN_HOST }}
  SIYUAN_TOKEN: ${{ secrets.SIYUAN_TOKEN }}
  SIYUAN_BOX: ${{ secrets.SIYUAN_BOX }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
  push:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: upload -r ./public/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
