name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VALINE_APPID: ${{ secrets.VALINE_APPID }}
          envkey_VALINE_APPKEY: ${{ secrets.VALINE_APPKEY }}
          envkey_SIYUAN_HOST: ${{ secrets.SIYUAN_HOST }}
          envkey_SIYUAN_TOKEN: ${{ secrets.SIYUAN_TOKEN }}
          envkey_SIYUAN_BOX: ${{ secrets.SIYUAN_BOX }}
          file_name: .env.production
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -r ./public/ /
          secret_id: ${{ secrets.COS_SECRET_ID }}
          secret_key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}

